type Query {
    bookById(id: ID): Book
}

type Book {
    id: ID
    name: String
    pageCount: Int
    totalPages: Int # same as pageCount
    author: Author
}

type Author {
    id: ID
    firstName: String
    lastName: String
}